#!/bin/sh

uci set system.@system[0].timezone=MSK-3MSD
uci set system.@system[0].zonename=Europe/Moscow
uci commit system

sed -i 's/root::0:0:99999:7:::/root:$1$V4UetPzk$CYXluq4wUazHjmCDBCqXF.:0:0:99999:7:::/g' /etc/shadow

exit 0
